spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sphinx
    username: postgres
    password: qwerdf123 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  port: 8085
