# application-prod.yml (production environment)
spring:
  application:
    name: sphinx-server
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}?sslmode=require
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

server:
  port: ${PORT:8085}