# application-prod.yml (production environment)
spring:
  application:
    name: sphinx-server
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}?sslmode=require
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  port: ${PORT:8085}
  servlet:
    session:
      cookie:
        secure: true
        same-site: none
      timeout: 30m