name: Deploy to Render

# This workflow runs when code is pushed to master or when a pull request is created
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # First job: Run tests to ensure code quality
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Run tests using Gradle
      - name: Run tests
        run: ./gradlew test

  # Second job: Deploy to Render (only runs after tests pass and only on master branch)
  deploy:
    needs: test
    runs-on: ubuntu-latest
    # Only deploy when pushing to master branch
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - name: Trigger Render Deployment
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
            -H "accept: application/json" \
            -H "authorization: Bearer $RENDER_API_KEY"